apiVersion: apps/v1
kind: Deployment
metadata:
  name:  second-app
  labels:
    app:  my-app
spec:
  selector:
    matchLabels:
      app: second-app
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  second-app
    spec:
      containers:
      - name: second-app
        image: abdelrhmandevops/second-app
        ports:
        - containerPort: 8888
        env:
        - name: API_URL
          value: first-service/json
            
        
      restartPolicy: Always
