apiVersion: v1
kind: Service
metadata:
  name: second-service
spec:
  type: NodePort
  selector:
    app : second-app
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30002
